// createPerson.test.js
const createPerson = require('./createPerson')

test('must have expected properties', () => {
  const p = createPerson()
  expect(typeof p.firstName).toBe('string')
  expect(typeof p.lastName).toBe('string')
  expect(typeof p.jobArea).toBe('string')
  expect(typeof p.sex).toBe('string')
  expect(typeof p.birthday).toBe('object')
  expect(p.birthday.constructor.name).toBe('Date')
  expect(typeof p.address).toBe('object')
  expect(typeof p.address.street).toBe('string')
  expect(typeof p.address.suite).toBe('string')
  expect(typeof p.address.city).toBe('string')
  expect(typeof p.address.zipcode).toBe('string')
  expect(typeof p.address.geo).toBe('object')
  expect(typeof p.address.geo.lat).toBe('string')
  expect(typeof p.address.geo.lng).toBe('string')
})
